# Form implementation generated from reading ui file 'ui\main_screen.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_screen(object):
    def setupUi(self, main_screen):
        main_screen.setObjectName("main_screen")
        main_screen.resize(900, 600)
        main_screen.setStyleSheet("QDialog {\n    background-color: #f5f5f5;\n}\nQLineEdit {\n    border: 2px solid #ddd;\n    border-radius: 5px;\n    padding: 5px;\n    background-color: white;\n    font-size: 12px;\n}\nQLineEdit:focus {\n    border: 2px solid #4CAF50;\n}\nQTableView {\n    background-color: white;\n    border: 1px solid #ddd;\n    border-radius: 5px;\n    gridline-color: #eee;\n    font-size: 12px;\n}\nQTableView::item {\n    padding: 5px;\n}\nQTableView::item:selected {\n    background-color: #e3f2fd;\n}\nQHeaderView::section {\n    background-color: #f0f0f0;\n    padding: 5px;\n    border: none;\n    border-right: 1px solid #ddd;\n    border-bottom: 1px solid #ddd;\n    font-weight: bold;\n}")
        self.verticalLayout = QtWidgets.QVBoxLayout(main_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterEdit = QtWidgets.QLineEdit(parent=main_screen)
        self.filterEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.filterEdit.setClearButtonEnabled(True)
        self.filterEdit.setObjectName("filterEdit")
        self.verticalLayout.addWidget(self.filterEdit)
        self.pluginsView = QtWidgets.QTableView(parent=main_screen)
        self.pluginsView.setMinimumSize(QtCore.QSize(0, 400))
        self.pluginsView.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pluginsView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.pluginsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.pluginsView.setSortingEnabled(True)
        self.pluginsView.setWordWrap(False)
        self.pluginsView.setObjectName("pluginsView")
        self.pluginsView.horizontalHeader().setMinimumSectionSize(50)
        self.pluginsView.horizontalHeader().setDefaultSectionSize(150)
        self.pluginsView.horizontalHeader().setStretchLastSection(True)
        self.pluginsView.verticalHeader().setVisible(False)
        self.pluginsView.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.pluginsView)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.selectDirtyButton = QtWidgets.QPushButton(parent=main_screen)
        self.selectDirtyButton.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.selectDirtyButton.setFont(font)
        self.selectDirtyButton.setStyleSheet("QPushButton {\n    background-color: #FF6B6B;\n    color: white;\n    border: none;\n    border-radius: 5px;\n    padding: 5px;\n}\nQPushButton:hover {\n    background-color: #FF5252;\n}\nQPushButton:pressed {\n    background-color: #E53935;\n}")
        self.selectDirtyButton.setAutoDefault(False)
        self.selectDirtyButton.setObjectName("selectDirtyButton")
        self.buttonsLayout.addWidget(self.selectDirtyButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(parent=main_screen)
        self.okButton.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("QPushButton {\n    background-color: #4CAF50;\n    color: white;\n    border: none;\n    border-radius: 5px;\n    padding: 5px;\n}\nQPushButton:hover {\n    background-color: #45a049;\n}\nQPushButton:pressed {\n    background-color: #3d8b40;\n}")
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(False)
        self.okButton.setObjectName("okButton")
        self.buttonsLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=main_screen)
        self.cancelButton.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton {\n    background-color: #f44336;\n    color: white;\n    border: none;\n    border-radius: 5px;\n    padding: 5px;\n}\nQPushButton:hover {\n    background-color: #d32f2f;\n}\nQPushButton:pressed {\n    background-color: #b71c1c;\n}")
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(main_screen)
        self.cancelButton.clicked.connect(main_screen.reject) # type: ignore
        self.okButton.clicked.connect(main_screen.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(main_screen)

    def retranslateUi(self, main_screen):
        _translate = QtCore.QCoreApplication.translate
        main_screen.setWindowTitle(_translate("main_screen", "Batch Plugin Cleaner"))
        self.filterEdit.setPlaceholderText(_translate("main_screen", "Filter..."))
        self.selectDirtyButton.setText(_translate("main_screen", "选择所有红色脸"))
        self.okButton.setText(_translate("main_screen", "OK"))
        self.cancelButton.setText(_translate("main_screen", "Cancel"))
        self.cancelButton.setShortcut(_translate("main_screen", "Esc"))
