# Form implementation generated from reading ui file 'ui\main_screen.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_screen(object):
    def setupUi(self, main_screen):
        main_screen.setObjectName("main_screen")
        main_screen.resize(923, 1103)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterEdit = QtWidgets.QLineEdit(parent=main_screen)
        self.filterEdit.setClearButtonEnabled(True)
        self.filterEdit.setObjectName("filterEdit")
        self.verticalLayout.addWidget(self.filterEdit)
        self.pluginsView = QtWidgets.QTableView(parent=main_screen)
        self.pluginsView.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.pluginsView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.pluginsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.pluginsView.setSortingEnabled(True)
        self.pluginsView.setObjectName("pluginsView")
        self.pluginsView.horizontalHeader().setStretchLastSection(True)
        self.pluginsView.verticalHeader().setVisible(False)
        self.pluginsView.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.pluginsView)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(parent=main_screen)
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(False)
        self.okButton.setObjectName("okButton")
        self.buttonsLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=main_screen)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(main_screen)
        self.cancelButton.clicked.connect(main_screen.reject) # type: ignore
        self.okButton.clicked.connect(main_screen.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(main_screen)

    def retranslateUi(self, main_screen):
        _translate = QtCore.QCoreApplication.translate
        main_screen.setWindowTitle(_translate("main_screen", "Batch Plugin Cleaner"))
        self.filterEdit.setPlaceholderText(_translate("main_screen", "Filter..."))
        self.okButton.setText(_translate("main_screen", "OK"))
        self.cancelButton.setText(_translate("main_screen", "Cancel"))
        self.cancelButton.setShortcut(_translate("main_screen", "Esc"))
